### ISSUE TITLE
Tests fail with Mojolicious 6.22

### ISSUE THREAD

**Issue by eserte** [oetiker/mojolicious-plugin-pingen#1]
01async.t fails, probably only if Mojolicious 6.22 is installed:

```
Output from '/usr/bin/make test':

PERL_DL_NONLAZY=1 "/usr/perl5.16.3t/bin/perl5.16.3" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t

#   Failed test 'exact match for JSON Pointer "/error"'
#   at t/01async.t line 62.
#     Structures begin differing at:
#          $got = 0
#     $expected = '0'
# Looks like you failed 1 test of 12.
t/01async.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests 
```

This happens with 0.2.0 and 0.2.1.

**Comment by oetiker** [comment]
I am on it ... :) but if you have suggestions ... by all means!

**Comment by eserte** [comment]
Your plugin is not the only "victim" of this change in Mojolicious 6.22:
- https://github.com/jberger/Galileo/issues/47
- https://github.com/jhthorsen/swagger2/issues/38
- https://rt.cpan.org/Ticket/Display.html?id=107378

Maybe it's an unwanted regression in Mojolicious itself and should be reported there?

**Comment by oetiker** [comment]
the problem seems to be that it does not do automatic type conversion anymore when checking json values ...

**Comment by eserte** [comment]
0.2.2 looks good: http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-Pingen%200.2.2
